# Generated by Django 5.0 on 2023-12-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_name",
                    models.CharField(max_length=200, verbose_name="商家用户名"),
                ),
                ("real_name", models.CharField(max_length=200, verbose_name="真实姓名")),
                (
                    "merchant_password",
                    models.CharField(max_length=200, verbose_name="商家密码"),
                ),
                (
                    "merchant_sex",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=20,
                        verbose_name="性别",
                    ),
                ),
                (
                    "merchant_phone",
                    models.CharField(max_length=20, verbose_name="商家手机号"),
                ),
                (
                    "merchant_register_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="商家注册时间"),
                ),
            ],
        ),
    ]
