# Generated by Django 5.0 on 2023-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Merchant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={
                "ordering": ["-merchant_register_time"],
                "verbose_name": "商户信息",
                "verbose_name_plural": "商户信息",
            },
        ),
    ]
