# Generated by Django 5.0 on 2023-12-08 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Merchant", "0002_alter_merchant_options"),
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsinfo",
            name="merchant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Merchant.merchant",
                verbose_name="商家",
            ),
        ),
    ]
