# Generated by Django 5.0 on 2023-12-04 13:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=40, unique=True, verbose_name="用户名"),
                ),
                ("user_pwd", models.CharField(max_length=128, verbose_name="用户密码")),
                (
                    "user_real_name",
                    models.CharField(max_length=40, verbose_name="真实姓名"),
                ),
                (
                    "user_sex",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=20,
                        verbose_name="性别",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "user_addr",
                    models.CharField(default="", max_length=128, verbose_name="收货地址"),
                ),
                (
                    "user_postal_code",
                    models.CharField(default="", max_length=6, verbose_name="邮编"),
                ),
                (
                    "user_tel",
                    models.CharField(default="", max_length=11, verbose_name="联系方式"),
                ),
                (
                    "user_register_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "ordering": ["-user_register_time"],
            },
        ),
        migrations.CreateModel(
            name="GoodsBrowser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "browser_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="浏览时间"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsinfo",
                        verbose_name="商品ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userinfo",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户浏览记录",
                "verbose_name_plural": "用户浏览记录",
            },
        ),
    ]
