# Generated by Django 5.0 on 2023-12-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTotalInfo",
            fields=[
                (
                    "orderID",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="总订单ID",
                    ),
                ),
                (
                    "order_time",
                    models.DateTimeField(auto_now=True, verbose_name="下单时间"),
                ),
                ("order_pay", models.BooleanField(default=False, verbose_name="是否支付")),
                (
                    "order_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总价"
                    ),
                ),
                ("order_addr", models.CharField(max_length=128, verbose_name="订单收货地址")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userinfo",
                        verbose_name="订单用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
            },
        ),
        migrations.CreateModel(
            name="OrderPartInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="商品价格"
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="商品数量")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodsinfo",
                        verbose_name="商品",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.ordertotalinfo",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单详情",
                "verbose_name_plural": "订单详情",
            },
        ),
    ]
