# Generated by Django 5.0 on 2023-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_ordertotalinfo_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpartinfo",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="订单价格"
            ),
        ),
        migrations.AlterField(
            model_name="ordertotalinfo",
            name="orderID",
            field=models.AutoField(
                max_length=30, primary_key=True, serialize=False, verbose_name="总订单ID"
            ),
        ),
    ]
