# Generated by Django 5.0 on 2023-12-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Merchant", "0002_alter_merchant_options"),
        ("order", "0003_alter_orderpartinfo_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertotalinfo",
            name="merchant",
        ),
        migrations.AddField(
            model_name="orderpartinfo",
            name="merchant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Merchant.merchant",
                verbose_name="商家",
            ),
        ),
    ]
