# Generated by Django 5.0 on 2024-01-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_remove_ordertotalinfo_merchant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertotalinfo",
            name="orderID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="总订单ID"
            ),
        ),
    ]
